### ISSUE TITLE
NPM Package

### ISSUE THREAD

**Issue by slavanga** [christian-beckmann/parcel-transformer-twig#1]
Thank you for creating this plugin. It's very useful ☺
Would be nice to have it published on NPM. Let me know if I can help.

**Comment by christian-beckmann** [comment]
You're welcome. I don't know why this didn't happen, although it was already published with 

   npm publish

**Comment by slavanga** [comment]
@christian-beckmann Maybe try publishing the package with the following command:
`npm publish --access public`

This seems to be necessary when publishing public organization packages.
https://docs.npmjs.com/creating-and-publishing-an-organization-scoped-package#publishing-a-public-organization-scoped-package

**Comment by christian-beckmann** [comment]
Have successfully executed your command. Hope it goes online soon.

**Comment by slavanga** [comment]
@christian-beckmann Ok, seems like it did not work yet. The package was published as GitHub package. You can publish it to NPM using this command:
`npm publish --registry=https://registry.npmjs.org --access public`

**Comment by christian-beckmann** [comment]
@slavanga: Wow this is so complicated. I successfully runned your command. Hopefully this helps.

**Comment by slavanga** [comment]
@christian-beckmann Not sure why this still did not work tbh. Could be possible that the publishConfig in `package.json` is overriding the `--registry` parameter. Just a wild guess...

**Comment by christian-beckmann** [comment]
@slavanga So next try, a new release tag 0.0.9. Runned: npm publish --registry=https://registry.npmjs.org --access public

**Comment by slavanga** [comment]
@christian-beckmann Nice, it worked!
https://www.npmjs.com/package/@christian-beckmann/parcel-transformer-twig

Now if you want to keep the package current on the GitHub registry too, you probably need to publish again using this command:
`npm publish --registry=https://npm.pkg.github.com --access public`

**Comment by christian-beckmann** [comment]
@slavanga Many thanks to you :) it was a long way to publish.
