### ISSUE TITLE
It does not render the templates passed by other transformer

### ISSUE THREAD

**Issue by balthild** [christian-beckmann/parcel-transformer-twig#3]
Says, there's a file `a.twig.tpl` with content of `aaa`. A custom transformer (see the note below) will turn its content to `bbb` and set its type to `'twig'`. It's expected that `parcel-transformer-twig` should renders `bbb`, but actually it renders `aaa`.

At commit 01eae60ba54ca8f00914df416510f2fddc81a0ba, I see that this transformer is changed to render the original content of the file, rather then the content given by `asset` object. What's the reason of this change?

---

An example of such custom transformers:

```js
const { Transformer } = require('@parcel/plugin');

module.exports = new Transformer({
    async transform({ asset }) {
        const source = await asset.getCode();
        const code = source.replace('a', 'b');
        asset.setCode(code)
        asset.type = 'twig';
        return [asset];
    }
});
```

**Comment by christian-beckmann** [comment]
@balthild I was misguided by the use of the correct data. Fix is published 0.1.1. Many thanks for your help.
