### ISSUE TITLE
Build HTML indentation

### ISSUE THREAD

**Issue by fadrnym** [christian-beckmann/parcel-transformer-twig#4]
hi, I'm using twig for my projects and I'm having a problem with formatting after the build. Can you please advise me how to format the html correctly? Thanks a lot!

Example:

`     </div>
                    </div>

                                            <div class="col-12 col-md-6 col-lg-7">
                            <div class="cta-section__item">
                                <div class="cta-section__img-wrapper">`

`<div class="swiper" data-swiper="">
        <div class="swiper-wrapper">
                            <div class="swiper__slide swiper-slide">

                                            <p class="swiper__description">
                            „Lorem ipsum dolor sit amet, consectetur adipiscing elit. Proin sed vulputate massa. Orci varius natoque penatibus et magnis dis parturient montes, nascetur ridiculus mus. Maecenas vehicula dapibus placerat. Mauris odio diam, tincidunt in volutpat at, bibendum et nibh.“
                        </p>`

**Comment by christian-beckmann** [comment]
hi, this plugin uses [twig.js](https://github.com/twigjs/twig.js), maybe you should a issue there?

**Comment by fadrnym** [comment]
Thank you. I will ask them.
